Metrics/LineLength:
  Max: 120
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
